version: "3"
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost/api
    env_file:
      - ./client/.env
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: backend
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env